
import {
  ArrowRight,
  Check,
  ChevronsUpDown,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  Loader2,
  Mail,
  MessageSquare,
  Moon,
  PanelLeft,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash,
  User,
  X,
  Workflow,
  Lock,
  TrendingUp,
  Repeat,
  Users,
  Eye,
  DollarSign,
  LayoutDashboard,
  Receipt,
  PlusSquare,
  Folders,
  BarChart3,
  ChevronsLeft,
  Euro,
  FileText,
  LineChart,
  Bell,
  UserCircle2,
  FolderKanban,
  BarChartBig,
  CheckCircle,
  ArrowLeft,
  Save,
  CalendarIcon,
  LogOut,
  ScanLine,
  Camera,
  Sparkles // Ajout de l'icône Sparkles
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User, // Generic user icon
  userCircle: UserCircle2, // User icon in a circle, good for avatars
  panelLeft: PanelLeft,
  lock: Lock,
  trendingUp: TrendingUp,
  repeat: Repeat,
  users: Users, // Group of users
  eye: Eye,
  dollarSign: DollarSign,
  layoutDashboard: LayoutDashboard,
  receipt: Receipt,
  plusSquare: PlusSquare,
  folders: Folders,
  barChart3: BarChart3,
  chevronsLeft: ChevronsLeft,
  euro: Euro,
  fileText: FileText,
  lineChart: LineChart,
  bell: Bell,
  folderKanban: FolderKanban,
  barChartBig: BarChartBig,
  save: Save,
  calendar: CalendarIcon,
  logOut: LogOut,
  scan: ScanLine,
  camera: Camera,
  sparkles: Sparkles, // Ajout de l'icône Sparkles
};

export { Icons };

    