import {ArrowRight, Check, ChevronsUpDown, Circle, Copy, Edit, ExternalLink, File, HelpCircle, Home, Loader2, Mail, MessageSquare, Moon, PanelLeft, Plus, PlusCircle, Search, Server, Settings, Share2, Shield, Sun, Trash, User, X, Workflow, Lock, TrendingUp, Repeat, Users, Eye, DollarSign, LayoutDashboard, Receipt, PlusSquare, Folders, BarChart3, ChevronsLeft, Euro, FileText, LineChart, Bell, UserCircle, FolderKanban, BarChartBig, CheckCircle, ArrowLeft, Save, CalendarIcon, LogOut } from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  check: Check,
  checkCircle: CheckCircle,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  panelLeft: PanelLeft,
  lock: Lock,
  trendingUp: TrendingUp,
  repeat: Repeat,
  users: Users,
  eye: Eye,
  dollarSign: DollarSign,
  layoutDashboard: LayoutDashboard,
  receipt: Receipt,
  plusSquare: PlusSquare,
  folders: Folders,
  barChart3: BarChart3,
  chevronsLeft: ChevronsLeft,
  euro: Euro,
  fileText: FileText,
  lineChart: LineChart,
  bell: Bell,
  userCircle: UserCircle,
  folderKanban: FolderKanban, 
  barChartBig: BarChartBig, 
  save: Save,
  calendar: CalendarIcon,
  logOut: LogOut,
};

export {Icons};
